---
title: "PM566-lab3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

 ## step1 read in data
```{r}

if(!require(data.table)) {
  install.packages("data.table")}

if (!file.exists("met_all.gz")) {
download.file("https://raw.githubusercontent.com/USCbiostats/data-science-data/master/02_met/met_all.gz", 
              destfile = "met_all.gz", 
              method="libcurl", 
              timeout = 60)
}

met <- data.table::fread("met_all.gz")
```
 
 ##step 2 
```{r}
dim(met)
head(met, n=1)
tail(met)
```
 
## Step3:take a look at the variables
```{r}
str(met)
```


##Step4 
```{r}
#looking at categorical variables
table(met$year)
table(met$day)
table(met$hour)
```

```{r}
#looking at numerical variables
summary(met$temp)
summary(met$elev)
summary(met$wind.sp)
```

```{r}
met$elev[met$elev==9999.0] <- NA
#or
# met[elev == 9999.0, elev:= NA]
summary(met$elev)
```

The highest weather station is at `r max(met$elev, na.rm=TRUE)` 
Now we need to fix the temperature and summarize!

```{r}
met <- met[temp>-15][order(temp)]
summary(met[, .(lat, lon, wind.sp, temp, elev)])
```
##Step5
:p

## Step6 calculate summary statistics
```{r}
met[elev==max(elev, na.rm =TRUE)][, summary(wind.sp)]
met[elev==max(elev, na.rm =TRUE)][, summary(temp)]
```

```{r}
met[elev==max(elev, na.rm =TRUE), .(
  temp_wind = cor(temp, wind.sp, use = "complete"),
  temp_day = cor(temp, day, use = "complete"),
  temp_hour = cor(temp, hour, use = "complete"),
  wind_day = cor(wind.sp, day, use = "complete"),
  wind_hour = cor(wind.sp, hour, use = "complete")
)]
```

##Exploratory graphs

```{r}
hist(met$elev, breaks = 100)
```


